### ISSUE TITLE
0.6.0-devpreview not working

### ISSUE THREAD

**Issue by JeffInMadison** [dirkvranckaert/touchinputdisplaydriver#1]
I'm trying your wrapper on my app on 0.6.0-devpreview and my app works fine but if I have my Application class override TouchScreenDriverApplication with the waveshare profile I no longer see my main activity layout. I also cloned your demo app and cannot get the layout in the main activity to show.

Looking at what the wrapper does I'm a little surprised it is messing with the layout. Am I missing something? 

I am using this dependency:
compile 'eu.vranckaert.driver:touch:1.0.0'

**Comment by JeffInMadison** [comment]
Not only did I need to add:

`<uses-permission android:name="com.google.android.things.permission.MANAGE_INPUT_DRIVERS" />`

to the AndroidManifest.xml but you need to reboot the device for the permissions to be affective

> Dangerous permissions requested by apps are not granted until the next device reboot. This includes new app installs and new elements in existing apps.

**Comment by dirkvranckaert** [comment]
Thans for the report. No time yet to upgrade my boards but I will look into
this issue next week!

Dirk

Op vr 15 dec. 2017 06:13 schreef Jeff Alexander <notifications@github.com>:

**Comment by dirkvranckaert** [comment]
@JeffInMadison can, you try to update to 0.6.1? Didn't try myself yet but quickly looking at the changelog they might have fixed some stuff they might have broken...

**Comment by dirkvranckaert** [comment]
Just released the update with fix (v1.0.1), it's available on jcenter!
