### ISSUE TITLE
About Prerequest

### ISSUE THREAD

**Issue by howtowhy** [dirkvranckaert/touchinputdisplaydriver#11]
Hello dirk,
Thank you so much for contribution to Android things developer.
I am using Waveshare 3.5 inch display for my android things project.
I want to use your driver for my touch input.
but I have a trouble. In your read me, the pre-request was like this.

--------------------------------------------------------------------------------------------------------------
Prerequisites
Before using the driver you need to make sure you have the Input Device Confguration file (.idc) installed on your Android things device. To do so mount the SD card of your Android Things device and in the root partition under /system/usr/idc/ you should copy the AndroidTouchInputDriver.idc file that is available in the root of this project. If you do not copy that file the driver will work but Android will think that the driver is a physical mouse, which obviously results in totally different behaviour.

---------------------------------------------------------------------------------------------------------------

I flash my android things os on rasberry pie board (in lastest version)
and searched the "system/usr/idc/" path in sd card.
but there is not that path... how can I deal this problem?

is it use different image from normal android things os image?
also, where can I get "Input Device Confguration file (.idc)" ?
please tell me the link....

I am very appreciate your contribution :) please reply... :+1:

**Comment by dirkvranckaert** [comment]
Sorry for this late reply!
First of all the IDC file is available here: https://github.com/dirkvranckaert/touchinputdisplaydriver/blob/master/AndroidTouchInputDriver.idc (at the root of the repo).

I don't have a device available where I am right now but you should look in the different partitation that are created on your SD-card when you have the latest version of Android Things installed. There should be a directory /system/usr/idc in one of them.

Hope this helped you!

**Comment by TheLester** [comment]
MacOs can't see SD card with installed Android Things image. How I can copy this file?

**Comment by dirkvranckaert** [comment]
You need to be on a Windows or Linux machine (didn't get it working on my
mac through a VM either)...

Op zo 18 nov. 2018 om 22:46 schreef Dmitry <notifications@github.com>:
