### ISSUE TITLE
Driver.java no longer compiles with 0.8-devpreview

### ISSUE THREAD

**Issue by kkazakov** [dirkvranckaert/touchinputdisplaydriver#3]
It looks like it no longer works with 0.8-devpreview ... 

First **InputDriver.Builder(InputDevice.SOURCE_TOUCHSCREEN)** fails, and second the **mInputDriver.emit(touchInput.x, touchInput.y, touchInput.touching);** fails too. For the latter, it can be substituted with InputDriverEvent, but the first error I could not try a way to fix.

My only solution (for now) is to force 0.7-devpreview, which sadly doesn't work on 0.8 image.

**Comment by dirkvranckaert** [comment]
I have just solved this today with the latest commits to be compatible with 1.2!
