### ISSUE TITLE
Driver for MPI3508 on Android Things

### ISSUE THREAD

**Issue by classeasoft** [dirkvranckaert/touchinputdisplaydriver#4]
Is there any way to build a driver for MPI3508? I saw their hub https://github.com/goodtft/LCD-show but with no support for AT.

Is there any chance?

**Comment by dirkvranckaert** [comment]
Normally it should be possible. If I could get a hand on one of those screens to test with I should have something up an running in a few hours!
Do you know where we can get one? A development screen (meaning for free) would be awesome...

**Comment by dirkvranckaert** [comment]
Closing this issue after more than 3 months of inactivity
